### ISSUE TITLE
Compiling error help me pls

### ISSUE THREAD

**Issue by Shivats** [Michidu/MonoInjector#1]
Hi man I've tried to compile and i have that error thanks
![image](https://user-images.githubusercontent.com/21022177/28904899-4f1b9176-780e-11e7-84a8-17abbda2bea6.png)

**Comment by Michidu** [comment]
Choose "Release" mode.

**Comment by Shivats** [comment]
Thank you !

**Comment by Shivats** [comment]
Hey man can you explain me what is Init class and Init Method ? When i'm trying to inject i got that error 
![image](https://user-images.githubusercontent.com/21022177/28951863-d6075b88-78cd-11e7-8597-fc07b0610ab0.png)
