### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by MarshMello0** [Michidu/MonoInjector#5]
I can't seem to get this to compile successfully and have no clue what these errors mean
![image](https://user-images.githubusercontent.com/33008390/56867445-38043700-69dd-11e9-932c-e7cfaa9f3ed3.png)

**Comment by MarshMello0** [comment]
Some information, its using Windows SDK version 10.0.17763.0. I am running Visual Studio Community 2017 Version 15.9.11

**Comment by NexSqaud** [comment]
try use c++ 17 standart
